version: '2.3'
services:
  cuda:
    build: .
    volumes:
      - .:/user/src/app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: /bin/bash
    tty: true
    stdin_open: true
    container_name: cuda
